config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home/secret'

  root 'home#index'
  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
  end

  def secret
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

def create
  @project = Project.new(project_params)

  if @project.save
    redirect_to @project, notice: 'Project has been created.'
  else
    render :new
  end
end

  def show
  end


  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p>Home</p>
<%= link_to "New Project", new_project_path %>

app/views/home/secret.html.erb
ssshhh... :)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timesheets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
      <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
      <% end %>


    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= form_for(@project) do |f| %>
<p>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />

</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_field :description %><br />
</p>
    <%= f.submit %>
<% end %>